version: '3.8'

services:
  web:
    build: .
    working_dir: /tournaments-api-ui
    entrypoint: ["sh", "-c"]
    command: ["yarn install && yarn start"]
    environment:
      PORT: 3001
      YARN_CACHE_FOLDER: /yarn_cache
    ports:
      - '3001:3001'
    tty: true
    stdin_open: true
    volumes:
      - .:/tournaments-api-ui
      - node-modules:/tournaments-api-ui/node_modules
      - yarn-cache:/yarn_cache

volumes:
  node-modules:
  yarn-cache:
